I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script
    diosa "Bienvenido"
NameError: name 'Ruby' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script
    diosa "Bienvenido"
  File "C:\Users\Sofia\Documents\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Sofia\Documents\Renpy\renpy-8.0.3-sdk\renpy\exports.py", line 1473, in say
    who(what, *args, **kwargs)
  File "C:\Users\Sofia\Documents\Renpy\renpy-8.0.3-sdk\renpy\character.py", line 1332, in __call__
    who = renpy.python.py_eval(who)
  File "C:\Users\Sofia\Documents\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Sofia\Documents\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'Ruby' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.1.23060707
Laberinto de sucesos 0 1.0
Mon Sep  4 19:21:05 2023
